In [1]:
import pandas as pd
import sys
import os

# Add the parent directory to sys.path so src can be imported
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

import src.utils as utils

In [2]:
# Path relativo desde notebooks/ hasta data/raw/
ruta_corpus = "../data/raw/Corpus_completo_revisado.xlsx"

corpus_completo = pd.read_excel(ruta_corpus, engine="openpyxl")

In [3]:
corpus_completo

,Diario,Autor,Fecha,Título,Texto,Vínculo,ID
0,El Espectador,Gonzalo Hernández,1 de enero de 2018,Fajardo: para nada tibio,"La Coalición Colombia –Partido Alianza Verde, ...",https://web.archive.org/web/20180102104221/htt...,1
1,El Espectador,Eduardo Barajas Sandoval,1 de enero de 2018,Macedonia de Norte,Las interpretaciones de la historia sirven com...,https://web.archive.org/web/20180102104221/htt...,2
2,El Espectador,Daniel Emilio Rojas Castro,1 de enero de 2018,El nacionalismo según Vargas Llosa,La semana pasada Mario Vargas Llosa publicó un...,https://web.archive.org/web/20180102104221/htt...,3
3,El Espectador,Reinaldo Spitaletta,1 de enero de 2018,"Tiempo sagrado, tiempo profano","Pudiera decirse, sin ser una verdad absoluta, ...",https://web.archive.org/web/20180102104221/htt...,4
4,El Espectador,Aura Lucía Mera,1 de enero de 2018,La rebelión de los bueyes,Lo mejor del encierro de Las Ventas fueron los...,https://web.archive.org/web/20180102104221/htt...,5
...,...,...,...,...,...,...,...
13671,Semana,Gonzalo Sánchez,4 de junio de 2019,Es hora de salir de la trampa,Colombia tiene que liberarse del debate sobre ...,https://web.archive.org/web/20190605212054/htt...,13672
13672,Semana,Álvaro Jiménez,3 de junio de 2019,La semana de los propietarios,"Hemos avanzado mucho como país, para silenciar...",https://web.archive.org/web/20190605212117/htt...,13673
13673,Semana,Jairo Gómez,3 de junio de 2019,"Presidente, deje el estrés a un lado y gobierne","No pretendo, ni más faltaba, diseñarle las pol...",https://web.archive.org/web/20190605212129/htt...,13674
13674,Semana,Ana María Ruiz Perea,3 de junio de 2019,Era el mejor oficio del mundo,El periodismo que olisquea y escarba la realid...,https://web.archive.org/web/20190605220917/htt...,13675
13675,Semana,Julián de Zubiría Samper,3 de junio de 2019,¿Piensan los animales?,La pregunta de si los animales también piensan...,https://web.archive.org/web/20190605220937/htt...,13676

In [4]:
corpus_completo = utils.aplicar_funcion_fecha(corpus_completo)

In [5]:
corpus_completo

,Diario,Autor,Fecha,Título,Texto,Vínculo,ID
0,El Espectador,Gonzalo Hernández,2018-01-01,Fajardo: para nada tibio,"La Coalición Colombia –Partido Alianza Verde, ...",https://web.archive.org/web/20180102104221/htt...,1
1,El Espectador,Eduardo Barajas Sandoval,2018-01-01,Macedonia de Norte,Las interpretaciones de la historia sirven com...,https://web.archive.org/web/20180102104221/htt...,2
2,El Espectador,Daniel Emilio Rojas Castro,2018-01-01,El nacionalismo según Vargas Llosa,La semana pasada Mario Vargas Llosa publicó un...,https://web.archive.org/web/20180102104221/htt...,3
3,El Espectador,Reinaldo Spitaletta,2018-01-01,"Tiempo sagrado, tiempo profano","Pudiera decirse, sin ser una verdad absoluta, ...",https://web.archive.org/web/20180102104221/htt...,4
4,El Espectador,Aura Lucía Mera,2018-01-01,La rebelión de los bueyes,Lo mejor del encierro de Las Ventas fueron los...,https://web.archive.org/web/20180102104221/htt...,5
...,...,...,...,...,...,...,...
13671,Semana,Gonzalo Sánchez,2019-06-04,Es hora de salir de la trampa,Colombia tiene que liberarse del debate sobre ...,https://web.archive.org/web/20190605212054/htt...,13672
13672,Semana,Álvaro Jiménez,2019-06-03,La semana de los propietarios,"Hemos avanzado mucho como país, para silenciar...",https://web.archive.org/web/20190605212117/htt...,13673
13673,Semana,Jairo Gómez,2019-06-03,"Presidente, deje el estrés a un lado y gobierne","No pretendo, ni más faltaba, diseñarle las pol...",https://web.archive.org/web/20190605212129/htt...,13674
13674,Semana,Ana María Ruiz Perea,2019-06-03,Era el mejor oficio del mundo,El periodismo que olisquea y escarba la realid...,https://web.archive.org/web/20190605220917/htt...,13675
13675,Semana,Julián de Zubiría Samper,2019-06-03,¿Piensan los animales?,La pregunta de si los animales también piensan...,https://web.archive.org/web/20190605220937/htt...,13676

In [6]:
path_processed = r"..\data\processed"

corpus_completo.to_excel(os.path.join(path_processed, 'corpus_date_formatted.xlsx'), index=False)